//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTiengAnh.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int MaAD { get; set; }
        public string HoTenAD { get; set; }
        public string ĐiaChiAD { get; set; }
        public string DienThoaiAD { get; set; }
        public string TenDNAD { get; set; }
        public string PassAD { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string EmailAD { get; set; }
    }
}
