//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTiengAnh.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHoc
    {
        public int MaBH { get; set; }
        public string TenBH { get; set; }
        public string ChuDe { get; set; }
        public string AnhChuDe { get; set; }
        public string NoiDung { get; set; }
        public string NoiDungAnh { get; set; }
        public string NghiaTu { get; set; }
        public string NghiaTu2 { get; set; }
    }
}
