//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTiengAnh.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public int MaKQ { get; set; }
        public Nullable<int> MaHS { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<int> MaDe { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
